### ISSUE TITLE
unexpected behavior on different function declaration syntax

### ISSUE THREAD

**Issue by Andre-LA** [edubart/nelua-lang#114]
---

### Bug description

In Lua, `local function x() print 'hello world' end` is a syntax sugar to `local x = function() print 'hello world' end`, however, in nelua both can have different behaviors.

### Code example

```lua
local function A() print 'hello world' end
A()
```
output:
```sh
$ nelua test.nelua 
hello world
```
---
```lua
local A = function() print 'hello world' end
A()
```
output:
```sh
$ nelua test.nelua 
C compilation for '/home/dreunix/.cache/nelua/teste' failed:
/home/dreunix/.cache/nelua/teste.c: In function ‘teste_anonfunc’:
/home/dreunix/.cache/nelua/teste.c:101:17: error: expected expression before ‘{’ token
  101 |   nelua_print_1({(uint8_t*)"hello world", 11});
      |                 ^
```

### Expected behavior

The same behavior on both functions

### Environment

 - Nelua version:
 ```
Nelua 0.2.0-dev
Build number: 1270
Git date: 2021-08-28 08:05:55 -0300
Git hash: e11f12e03649502b997f78349241e1ed1c506704
 ``` 
 - Platform: `Pop!_OS 21.04`
 - Architecture: `x86_64`
 - C compiler: `gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1)`

**Comment by edubart** [comment]
The behavior is indeed different for optimization reasons, Nelua compiler treats `A` as a function variable in this syntax:

```lua
local A = function() print 'hello world' end
A()
```

While on the following `A` is a fixed function address (which generates more optimized code).

```lua
local function A() print 'hello world' end
A()
```

But you should not get errors like above, I will fix those.
