### ISSUE TITLE
Bug when closing parethesis is placed in new line for ## print()

### ISSUE THREAD

**Issue by stefanos82** [edubart/nelua-lang#115]
### Bug description

When I place the closing parenthesis of `## print()` in a new line, it breaks.

```
t.nelua:8:1: syntax error: unexpected syntax
)
^


shell returned 1
```

I'm trying to print the type(s) of nested `record`s and caused a bug by mistake.

### Code example

Provide minimal reproduction code to test the bug.
Please, format the code properly and try to keep it as simple as possible, just focusing on the experienced bug.

```lua
require 'string'

local A = @record{}
global A.B = @record{ x: integer}

## print(string.format("A.type: '%s'\nA.value.metafields.B: '%s'", A.type, A.value.metafields.B))
```

The problematic code looks like this:

```lua
require 'string'

local A = @record{}
global A.B = @record{ x: integer}

## print(
    string.format("A.type: '%s'\nA.value.metafields.B: '%s'", A.type, A.value.metafields.B)
)
```
### Expected behavior

It should print

```
A.type: 'type'
A.value.metafields.B: 'A.B: type = A.B'
```

### Workaround

If you have already found a way to workaround the issue,
then please share how you did it,
this may help others with the same issue.

### Environment

Provide relevant information about your environment:
 - Nelua version: 
 ```
Nelua 0.2.0-dev
Build number: 1268
Git date: 2021-08-27 13:07:25 -0300
Git hash: 97d5c391e12bb16b026e9d636b49ea18a42a8fd1
Copyright (C) 2019-2021 Eduardo Bart (https://nelua.io/)
```
 - Platform: GNU / Linux Debian
 - Architecture: `Linux debian 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 GNU/Linux`
 - C compiler: `gcc (Debian 10.2.1-6) 10.2.1 20210110`

**Comment by codehz** [comment]
I think it is expected.
you need to use ##[[ ]]## syntax for multiline preprocess

**Comment by stefanos82** [comment]
Indeed; good catch @codehz

**Comment by Andre-LA** [comment]
Indeed, however it doesn't need the `##` at the end, just `##[[ ]]` works¹, it follows the same rules as comments actually, so `##[==[ ]==]` can be used to avoid some `[[ ]]` conflict²:

¹ https://nelua.io/overview/#preprocessor
² https://nelua.io/overview/#preprocessor-code-blocks
