### ISSUE TITLE
solaris 11, tests/memory_test.nelua:114:36: runtime error: assertion failed!

### ISSUE THREAD

**Issue by tankf33der** [edubart/nelua-lang#117]
```
$ ./nelua.sh tests/memory_test.nelua 
tests/memory_test.nelua:114:36: runtime error: assertion failed!
  assert(memory.scan(p, 1, #@vec2) == &p.x)
                                   ^~~~~~~
$
```

**Comment by edubart** [comment]
Looks like SPARC is big-endian, so I've installed a big-endian system with QEMU, in my case I've used s390x architecture, and then checked the tests on it. In the process I've fixed that failing test and another issue, seems like now all tests are passing there.

Please, confirm for me later if all tests also pass on SPARC after commit https://github.com/edubart/nelua-lang/commit/178e35fe1d0d7edbb60149c77dcf34d542ef41df.

Thanks for reporting.
