### ISSUE TITLE
Unable to compile on DOS

### ISSUE THREAD

**Issue by leapofazzam123** [edubart/nelua-lang#119]
**WARNING: Please, read this note carefully before submitting a new bug:**

It is important to realize that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS ONLY.

If you need support, have questions, ideas to discuss you should use
the [Nelua Discussions](https://github.com/edubart/nelua-lang/discussions) forum or
the [Nelua Discord server](https://discord.gg/7aaGeG7).

Please, before submitting a new issue, verify the following:
 - You have tested it on latest Nelua version from master branch.
 - You have checked that there is no similar issue already reported.
 - You have checked that your code has no errors or misuse of Nelua.

---

### Bug description

A clear and concise description of the bug you are experiencing.
Tell what you were trying to do and what happened instead.

I'm trying to build Nelua on DOSBox-X using DJGPP, but it failed to compile. 
![Screenshot_20210831-215453](https://user-images.githubusercontent.com/76893443/131636106-e09b1d59-24c8-462c-90b9-ea87c8b92b89.png)

<!--### Code example

Provide minimal reproduction code to test the bug.
Please, format the code properly and try to keep it as simple as possible, just focusing on the experienced bug.

```lua
-- Place the Nelua code here.
```-->

### Expected behavior

A clear and concise description of what you expected to happen.

It should compile correctly

<!--### Workaround

If you have already found a way to workaround the issue,
then please share how you did it,
this may help others with the same issue.-->

### Environment

Provide relevant information about your environment:
 - Nelua version (you can check with `nelua -v`). Nelua from the master branch
 - Platform (e.g. Windows/MSYS2, Ubuntu Linux, MacOS) DOSBox-X
 - Architecture (e.g. x86_64, arm64) i386 (DOSBox-X)
 - C compiler if your bug has C compiler errors. (e.g. GCC 10.2, Clang 11) GCC 9.3.0

**Comment by edubart** [comment]
I've fixed those issues and others in https://github.com/edubart/nelua-lang/commit/41bf2606489ad535875f9f53aa9d7c9291740c59, but then lots of issues starts to appear, it's not worth to get Nelua compiler to work inside DOSBox, it's best to use it outside with DJGPP installed in your host OS, there are some binary releases for it at https://github.com/andrewwutw/build-djgpp/releases .

Then once you get DJGPP installed in your system, you should compile with the following line:
```shell
nelua --cc=i686-pc-msdosdjgpp-gcc --cflags="-march=i386 -lemu" -bo hello.exe examples/helloworld.nelua
```

Then copy `hello.exe` to DOSBox files and it show work.

In case you insist trying to compile `nelua-lua.exe` to use inside DOSBox, I was able to compile with the following line:

```shell
make SYS=Posix \
           CC=i686-pc-msdosdjgpp-gcc \
           NO_RPMALLOC=1 \
           CFLAGS="-march=i386 -lemu -D_longjmp=longjmp -D_setjmp=setjmp -Dgetc_unlocked=getc -Dflockfile=UNUSED -Dfunlockfile=UNUSED -DLUA_CPATH_DEFAULT='\"\"' -DLUA_DIRSEP='\"\\\\\"' -DLUA_PATH_DEFAULT='\".\\\\?.lua\"'"
```

This generates a working `nelua-lua.exe` that can run Lua scripts, but it's failing finding modules files, and I am not going or think it's worth to patch the Lua interpreter, so I've stopped there.
