### ISSUE TITLE
Possible bug with paths

### ISSUE THREAD

**Issue by stefanos82** [edubart/nelua-lang#127]
I have started writing a shell script to automate my Nelua tests and instead of going in the directory where the files are located, I have decided to let the script test them for me, from a separate location of course.

The script looks like this:

```sh
$ cat validatenelua.sh 
#!/bin/sh

tput reset

for name in /home/stefanos/code/nelua/*.nelua
do
    echo "$name"
    nelua -tb "$name"
done

for name in /home/stefanos/code/nelua/Overview/*.nelua
do
    echo "$name"
    nelua -tb "$name"
done
```
When executed from `$HOME/programming/` directory that is located, it throws an error for this particular module only:

![image](https://user-images.githubusercontent.com/1777466/134397283-b056a16a-c472-45e4-a16e-73b2a01bd547.png)

The interesting part is...when I go to `/home/stefanos/code/nelua/Overview/` and run `for name in *.nelua; do echo "$name"; nelua -tb "$name"; done`, everything works as expected.

Is it something that has to do with the relative / absolute paths?

I always confuse these two how they should work or behave.

My suspicion is telling me is related to https://github.com/edubart/nelua-lang/commit/b17a77b46b168016bd345e80b14ed0f435d42c24 where you introduced *support for relative requires in the preprocessor*.

**Comment by stefanos82** [comment]
Seems like it was a bug in my code; actually not a bug, but the old way of doing things.

After I rewrote `require 'globals` to `require ./globals.nelua`, now it works.

Can we add a note in the documentation to make it obvious for end-users that this should be the way of requiring modules that are relative to project's path?

**Comment by edubart** [comment]
> Seems like it was a bug in my code; actually not a bug, but the old way of doing things.
> 
> After I rewrote `require 'globals` to `require ./globals.nelua`, now it works.
> 
> Can we add a note in the documentation to make it obvious for end-users that this should be the way of requiring modules that are relative to project's path?

This is not the proper way to require modules relative to the same path, because it is platform dependent, while Linux uses `/` as path separator, windows uses `\`, you could use `require '.global'` instead. I don't want to document relative require yet because I don't want to encourage people to use it, as Lua can't do that, and people should really setup their library path instead, so it's a hidden feature.

**Comment by stefanos82** [comment]
> This is not the proper way to require modules relative to the same path, because it is platform dependent, while Linux uses `/` as path separator, windows uses `\`, you could use `require '.global'` instead. 

Like Python...interesting.

> I don't want to document relative require yet because I don't want to encourage people to use it, as Lua can't do that, and people should really setup their library path instead, so it's a hidden feature.

In Lua, how do you handle paths under Windows?

**Comment by stefanos82** [comment]
> Lua does this way: When you do `require 'path.to.file'`, the string `path.to.file` gets convert to `path/to/file.lua` on Linux and `path\to\file.lua` on Windows.

...and Nelua does not do that already to match Lua's behavior?

**Comment by edubart** [comment]
> ...and Nelua does not do that already to match Lua's behavior?

It does.

**Comment by stefanos82** [comment]
So what should be the Lua way to require modules relative to the same path as the one we need to run?

**Comment by edubart** [comment]
> So what should be the Lua way to require modules relative to the same path as the one we need to run?

This is not possible in Lua, the only thing you can do in Lua is to add search paths, in Nelua you can also add search paths with `--add-path` flag or in your config.

**Comment by stefanos82** [comment]
> This is not possible in Lua, the only thing you can do in Lua is to add search paths, in Nelua you can also add search paths with `--add-path` flag or in your config.

I see...
