### ISSUE TITLE
Weird behavior when messing with type inference

### ISSUE THREAD

**Issue by stefanos82** [edubart/nelua-lang#129]
I have hard time understanding how type inference works and decided to play more to finally grasp its semantics.

While I was doing so, the following code caused a problem:

```lua
require 'io'
require 'string'

do
  local msgv1 : auto = "hello"
  io.printf("%s from Nelua world!\n", msgv1)
  local msgv2 : string = "greetings"
  io.printf("%s from Nelua world!\n", msgv2)
  local msgv3 : type = #[msgv1.type]#
  io.printf("%s from New Nelua world!\n", msgv3)
end
```
![image](https://user-images.githubusercontent.com/1777466/134641800-542cddce-f645-439f-8746-e0ca6b930f3b.png)

The problem takes place when I attempt to use `#[msgv1.type]#` to get my first variable's type.

Now, I know that `local msgv3 : type = #[msgv1.type]#` is wrong and it should be `msgv3 : #[msgv1.type]# = "Saludos"` in order to work.

Why has it tried to build in the first place without complaining about its logic is the real question...

P.S.: would not it be nice to have a shortcut for types? For instance, in my case it could be `@""` to get the `string`s type.

**Comment by edubart** [comment]
You have discovered an unimplemented feature, that triggered a compile bug, thanks for reporting. I've fixed this in commit https://github.com/edubart/nelua-lang/commit/703bc2cbf708eb4c25114b554dbe4376d153d48f.

**Comment by stefanos82** [comment]
After reporting this issue, I've got curious to study the generated C code; of course the Nelua code has been tweaked (updated) a bit and now looks like this:

```lua
require 'io'

do
  local msgv1 : auto = "hello"
  io.printf("%s from Nelua world!\n", msgv1)
  io.printf(
    "'%s' is of type '%s'\n",
    #[tostring(msgv1.name)]#, #[tostring(msgv1.type)]#
  )
  local msgv2 : string = "greetings"
  io.printf("%s from Nelua world!\n", msgv2)
  local msgv3 : #[msgv1.type]# = "Saludos"
  io.printf("%s from New Nelua world!\n", msgv3)
end
```
What caught my attention in generated C code is the following line:

![image](https://user-images.githubusercontent.com/1777466/134766016-8d642360-783f-4f1f-9ffe-539f48759bd2.png)

Under which circumstances `if()` will not get executed?

**Comment by edubart** [comment]
> Under which circumstances `if()` will not get executed?

It will always be executed, the Nelua compiler does not simplify code of branches that are always true or false, but this is not a problem because the C compiler will simplify this at his optimizing stage. Nevertheless I've changed the code to not generate that `if(true)` anymore.

**Comment by stefanos82** [comment]
Ah I see, very well :+1:
