### ISSUE TITLE
can't preprocess "statement replacement macros" while unrolling

### ISSUE THREAD

**Issue by Andre-LA** [edubart/nelua-lang#131]
### Bug description

The compiler can't generate code with statement replacement macros inside a loop unrolling scope  

### Code example

```lua
## local function macrox(x)
  print(#[x]#)
## end

## for i = 1, 20 do
  #[macrox]#(10)
## end
```
output:
```
$ nelua test.nelua 
test.nelua:7:3: error: cannot convert preprocess value of type "function" to an AST node
  #[macrox]#(10)
  ^~~~~~~~~~
```

### Expected behavior

The same behaviour as repeating the code manually.

### Workaround

Wrap the statement replacement macro with a runtime function:
```lua
## local function macrox(x)
  print(#[x]#)
## end

local function macro_x(x: auto)
  #[macrox]#(x)
end

## for i = 1, 20 do
  macro_x(10)
## end
```

### Environment

Provide relevant information about your environment:
 - Nelua version: `0.2.0-dev.1365+e6a91c19`
 - Pop!_OS 21.04 (Ubuntu)
 - Architecture: x86_64

**Comment by edubart** [comment]
You have discovered a flaw in the replacement macro system, thanks for reporting this. I've fixed in commit https://github.com/edubart/nelua-lang/commit/7096f16a8a85cd0d30399505cf84f7a930636ec8
