### ISSUE TITLE
Proposal: Expression Blocks

### ISSUE THREAD

**Issue by resolritter** [edubart/nelua-lang#15]
An **Expression Block** is a scoped construct which yields the last evaluated value for a given branch.

Suppose an **Expression Block** would be syntactically defined as `expr ... end`, then the following block of code would work:

```lua
local baz = 3

local Foo = @record { bar: integer }

local foo: Foo = expr
  if baz == 3 then
    local tmp = baz + 1
    -- this the last evaluated expression, so it gets returned from this block automatically
    { bar = tmp  }
  else
    { bar = 0 }
  end
end
```

They are more powerful and flexible than ternary operators, mainly because other instructions can be put between the `if` s and the assignment (in this case, `local tmp = a`).

Expression Blocks don't bloat the syntax - they look very similar to how `do` and `block` ([from the draft](https://nelua.io/draft/#block)) constructs look like, thus there's no need to invent a special assignment syntax for ternary operators.

For inspiration:

- [F#'s computation expressions](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/computation-expressions#syntax-overview)
- [Rust's block expressions](https://doc.rust-lang.org/reference/expressions/block-expr.html)
- [Haskell's if expressions](https://en.wikibooks.org/wiki/Haskell/Control_structures#Embedding_if_expressions)
- [Haskell's case expressions](https://en.wikibooks.org/wiki/Haskell/Control_structures#case_expressions)

**Comment by DarkWiiPlayer** [comment]
Such a feature would be a huge break from Luas original design which emphasizes a small syntax that's both easy to parse and memorize.

Personally, I also think it makes the code very ugly, because it doesn't make it clear if the function really returns there or not.

**Comment by edubart** [comment]
> Such a feature would be a huge break from Luas original design which emphasizes a small syntax that's both easy to parse and memorize.

Indeed, and is in the heart of Nelua to have few syntax additions over Lua.

But a feature like this would be implemented as an extension, not in the core of the language, this is a interesting feature to demo how Nelua can extended its syntax in a blog post I may do in the future.

But yet the syntax has some issues, to make it work well with the parser it needs a keyword before the last expression, like `return`, but that would be confused with function returns. Will think more when tackling this extension.

**Comment by resolritter** [comment]
The alternative to Expression Blocks is to allow for the Lua equivalent: declare the variable without initializing it, then use `if` s to assign the value later.

This is Lua version which does the same as the proposal:

```lua
local a = 3
-- declare without initialization
local name

if a == 3 then
  local tmp = a
  name = tmp + 1
else
  name = 0
end
```

While it's more uniform and arguably simpler to grasp, the compiler go through every branch _after all expansions have been made_ to detect if the assignment has been done properly. The TypeScript compiler, for instance, does such analysis, so it's _conceptually_ doable, but I'm not sure if there would be some caveat to it in Nelua.

**Comment by resolritter** [comment]
I've updated the examples to use a struct instead of integer since the former is not automatically initialized (someone looking at the code might be misleading of it "working" already due to this quirk).

**Comment by edubart** [comment]
Worth noting that in Nelua you can avoid pre initialization of variables with `<noinit>` annotation. When doing this the efficiency and even the assembly generated code would be equivalent to this proposal. But from what I understood intent of the proposal is to creating a syntax to allow inlining statements inside expressions, thus would not need to use `<noinit>` annotation and would give more power for expressions, by allowing control flow statements inside them.

**Comment by resolritter** [comment]
The main use-case I would have in mind for this feature is exhaustive conditional assignment. `<noinit>` is the opposite as it doesn't check if the variable has been initialized properly

```
local Baz = @record { baz: integer }
local Foo = @record { bar: Baz }
local foo: Foo <noinit>

if false then
  foo = { bar = { baz = 1 } }
end

-- I want to guarantee Foo is initialized, so this is a problem
print(foo.bar.baz)
```

where as, with Expression Blocks, the expression is always guaranteed to have a initial value attached to it, which is the block's value.

Other than that, I can only think of creating a `<lateinit>` attribute and have the compiler check all branches to see if the variable has been initialized before usage. This attribute would be necessary to avoid automatic initialization, because it's not always the desired behavior.

**Comment by edubart** [comment]
This feature has been implemented in the core!

I've come across a situation where I needed this feature in the compiler to allow creating macros for expressions, so after implementing it I've exposed the feature with the following syntax:

```lua
local function is_positive(x: integer)
  local res = (do
    if x > 0 then
      return true
    else
      return false
    end
  end)
  return res
end

assert(is_positive(2) == true)
assert(is_positive(0) == false)
assert(is_positive(-1) == false)
```

Thus expression blocks can be created with `(do ... end)`, note that the parenthesis is required. There are many reasons for this syntax:
* It does not introduce new keywords
* The `return` keyword is required to make the parser know when the expression evaluation is finished
* The parenthesis are required because using `do .. end` without parenthesis would lead to ambiguous syntax:
```lua
local function f()
  if true then
    -- this syntax would be ambiguous
    -- is it a return of a statement expression?
    -- or a return with no arguments plus a do block?
    return
    do
       print 'something'
    end
  end
end
```
* Also is a common practice to surround expressions with parenthesis, so it is more clear to the user eyes.

**Comment by resolritter** [comment]
Looks great!
