### ISSUE TITLE
Attempt to use `math.random(0)` results in error

### ISSUE THREAD

**Issue by dcurrie** [edubart/nelua-lang#163]
### Bug description

Use of  `math.random(0)` results in error:

    /usr/local/lib/nelua/lib/math.nelua:555:16: runtime error: interval is empty
        check(high > 0, "interval is empty")

### Code example

```lua
n = math.random(0)
```

### Expected behavior

Per the documentation: "The call math.random(0) produces an integer with all bits (pseudo)random."

### Workaround

```lua
n = math.random(0, 0x7FFFFFFFFFFFFFFF)
```
but that only provides 63 bits

### Environment

 - Nelua version (you can check with `nelua -v`).
Nelua 0.2.0-dev
Build number: 1425
Git date: 2021-12-17 10:58:07 -0300
Git hash: 54f3d8e73ad430d58f5f43b8e1ee270201465511
Semantic version: 0.2.0-dev.1425+54f3d8e7
Copyright (C) 2019-2021 Eduardo Bart (https://nelua.io/)

 - Platform :  macOS
 - Architecture : x86_64 
 - C compiler : N/A but 
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix

**Comment by edubart** [comment]
Thanks for reporting, issue fixed in commit https://github.com/edubart/nelua-lang/commit/c001f51d6e4492b484124e1bcd498813d4c07b0b
