### ISSUE TITLE
Proposal: More straightforward API for injecting AST nodes into the source code

### ISSUE THREAD

**Issue by resolritter** [edubart/nelua-lang#17]
# Problem

Nelua's overview has this example

```
##[[
function unroll(count, block)
  for i=1,count do
    block()
  end
end
]]

local counter = 1
## unroll(4, function()
  print(counter) -- outputs: 1 2 3 4
  counter = counter + 1
## end)
```

This approach is limited

- Can't create intermediate variables without runtime cost.
- Can't memoize results - imagining if it was costly to compute the node: you'd need to compute the node 4 times, instead of only evaluating the macro once and returning the same value on future runs.
- Doesn't exemplify a way of using a return value for building the node.

---

What I would like to do is:

```
##[[
function ast_builder(input)
   return aster.Block { ... }
end
]]

## inject_my_ast(ast_builder(input))
```

i.e. be able to create new arbitrary AST nodes and inject it directly into the source code.

This would also be useful in, for instance, programmatically injecting generated bindings at compile time depending on some input (it would inject those `global EXTERNAL: T <cimport, nodecl>` nodes at some point in the program).

---

The following approach is currently viable

```
##[[
function my_macro(input)
  local n = aster
  return n.Block{{n.Call{{}, n.Id{'a'}}}}
end
]]

## ppcontext:add_statnode(my_macro(custom_input))
```

however, it exposes this `ppcontext` internal and also isn't documented.

# Proposal

- Create an API which exposes both `aster` and `ppcontext` through a common module for manipulating ASTs
- Create a wiki with community-contributed examples
- Compare the approach with `ppcontext:add_statnode` with what's called [Pre-processor macros](https://nelua.io/overview/#preprocessor-macros)

About the last point, from what I've seen so far, `ppcontext:add_statnode` is more powerful because it allows you to define a whole block of code arbitrarily, whereas **Pre-processor macros** have more limitations of where they can be injected, since they are manipulating **existing** source code AST instead of creating a new one.

**Comment by edubart** [comment]
Indeed, `ppcontext:add_statnode(my_macro(custom_input))` is not peasant, I need to think of a better name and make a global function in the preprocessor, I guess we could use the name `inject_ast`, `inject_node`, `inject_astnode` ? Ugh, I can't like any name, I really wanted some name small, simple and clear.

What I don't like at the moment is that the preprocessor already have many global functions populating its global environment, I want to keep that small, so I try to avoid adding new ones, but I don't see a better way at the moment, I could encapsulating in a table but that would make the code more verbose while metaprogramming.

Currently all these global functions/variables are visible in the preprocessor environment:
```
    afteranalyze
    afterinfer
    staticerror
    staticassert
    overload_concept
    optional_concept
    generic
    hygienize
    generalize
    memoize
    symbols
    pragmas
    context
    ppcontext
    ppregistry
    ast
    aster
    config
    types
    traits
    primtypes
```

I will document what are all of those later, each one have its use when meta programming, you can find some example usage of them in the sources.

Note that there is a `memoize` function that can memoize stuff (since you mentioned about memoize).

**Comment by edubart** [comment]
I've added the function `inject_astnode` in a recent commit, you can now do:

```lua
##[[
function ast_builder(input)
   return aster.Block { ... }
end
]]

## inject_ast(ast_builder(input))
```

**Comment by resolritter** [comment]
> I've added the function `inject_astnode` in a recent commit, you can now do:
> 
> ```lua
> ##[[
> function ast_builder(input)
>    return aster.Block { ... }
> end
> ]]
> 
> ## inject_ast(ast_builder(input))
> ```

That helps! IMO it's fine to have lots of modules available globally in the pre-processor , because that's more flexible than hiding the API for some arbitrary reason.

This issue is, overall, more about accessiblity. For instance, `pp_context` isn't very memorizable, nor it says something about what that module is useful for. Following "separation of concern" ideas, since there are two functions

- One builds the AST
- Another one injects it

It seems like they could live in the same module, API-wise. That doesn't imply having the implementation underneath would have change, as you could just create a "façade" module and re-export better-named APIs from them.

Naming is not so huge of a problem, though. The other points I've mentioned **Proposal** related to the documentation are more useful.

**Comment by edubart** [comment]
I think this can be closed, because now we have the `inject_astnode` preprocessor function and changes were made in the macro documentation to clarify how to create more flexible macros using custom AST nodes and this function.
