### ISSUE TITLE
Document how to modularize pre-processor macros

### ISSUE THREAD

**Issue by resolritter** [edubart/nelua-lang#18]
[Nelua's overview documentation](https://nelua.io/overview/#preprocessor-macros) shows the following pattern for defining new Pre-processor macros.

```
##[[
function unroll(count, block)
  for i=1,count do
    block()
  end
end
]]

-- code here
```

Problems:

- I might want to use this same definition in more than one module. How to achieve that?
- You can't format Lua code inside of a string.
- You also might not get syntax highlighting in the editor, since everything is wrapped into a string.
- Although it isn't very noticeable for one-off small functions, it doesn't feel good for it the whole thing to be embedded into a string for huge macros. It implies syntaxes limitations, e.g.

```
    foo = dict[bar[baz]]
                      ^ this `]]` breaks the syntax because the whole thing is inside of a multiline string
```

---

I would like to have **the option** to do the following: define an arbitrary Lua module which could have big and reusable macros

```lua
   function unroll(input)
       -- some code...
   end
```

then import it in my Nelua code

```
## require <macros> 'project.module' 
```

Their usage would only be valid inside of other pre-processor blocks.

**Comment by edubart** [comment]
> I might want to use this same definition in more than one module. How to achieve that?

You can already do this, and the mentioned example should work. The preprocessor on all scripts shares the same lua environment, that means if you define `function unroll()` in one file inside the preprocessor context, that function `unroll` will be really defined in the preprocessor environment, thus unroll will be visible on preprocessor contexts on all scripts after that definition, you can avoid this by declaring as `local function`.

> You also might not get syntax highlighting in the editor, since everything is wrapped into a string.

It's possible to do syntax highlighting inside the `#[[` `]]`, for instance the Sublime Text plugin for Nelua does syntax highlighting inside preprocessor context, so does the syntax highlighter in the docs website.

> Although it isn't very noticeable for one-off small functions, it doesn't feel good for it the whole thing to be embedded into a string for huge macros. It implies syntax limitations, e.g.

Actually like Lua, you can as many  `=` between the square brackets to avoid this issue, so you can do this to avoid that problem:
```lua
##[==[
 foo = dict[bar[baz]]
##]==]
```

If you don't like to wrap many code inside a huge `##[=[ ... ]=]` block, you can create a Lua file called `mymacros.lua` and just do:
```lua
## require `mymacros`

## mymacros.dosomething()
```

> I would like to have the option to do the following: define an arbitrary Lua module which could have big and reusable macros
The above answer provides this, using a separate `.lua` file and requiring with the preprocessor.

I will try to clarify all this in the documentations later, thanks for the questions!

**Comment by resolritter** [comment]
I'll submit an MR for updating the documentation with what I've learned here
