### ISSUE TITLE
--lua option doens't change the used lua interpreter

### ISSUE THREAD

**Issue by Andre-LA** [edubart/nelua-lang#19]
```sh
$ cat test.nelua 
## print("_VERSION: " .. _VERSION)
$ 
$ nelua test.nelua -q
_VERSION: Lua 5.4
$ 
$ nelua test.nelua -q --lua lua5.3 --lua-version 5.3
_VERSION: Lua 5.4
$ 
$ nelua test.nelua -q --lua lua5.3 --lua-version 5.3 --print-config
{
  add_path = { "/home/andre_la/Downloads/git/nelua-projs/nRotor/", "/home/andre_la/Downloads/git/nelua-projs/nelua-raylib/", "/home/andre_la/Downloads/git/nelua-projs/nprof/" },
  cache_dir = "nelua_cache",
  cc = "gcc",
  cflags = "",
  cpu_bits = 64,
  define = {},
  gdb = "gdb",
  generator = "c",
  input = "test.nelua",
  lib_path = "/usr/local/lib/nelua/lib",
  lua = "lua5.3",
  lua_version = "5.3",
  path = "./?.nelua;./?/init.nelua;/home/andre_la/Downloads/git/nelua-projs/nRotor//?.nelua;/home/andre_la/Downloads/git/nelua-projs/nRotor//?/init.nelua;/home/andre_la/Downloads/git/nelua-projs/nelua-raylib//?.nelua;/home/andre_la/Downloads/git/nelua-projs/nelua-raylib//?/init.nelua;/home/andre_la/Downloads/git/nelua-projs/nprof//?.nelua;/home/andre_la/Downloads/git/nelua-projs/nprof//?/init.nelua;/usr/local/lib/nelua/lib/?.nelua;/usr/local/lib/nelua/lib/?/init.nelua",
  pragma = {},
  quiet = true
}
```

Installed using `make`, when installed with `luarocks`, it uses `5.3`, but still can't change to, for example, `lua5.2`.

**Comment by edubart** [comment]
Actually that flag does not change which Lua interpreter is used to run the Nelua compiler. To do that you can do:
```
NELUA_LUA="lua5.3" ./nelua.sh myapp.nelua
```

Replace `./nelua.sh` with just `nelua` if you have installed nelua using `make install`.
Note this will not work with LuaRocks, when installing through LuaRocks you must edit the `~/.luarocks/bin/nelua` to manually change the Lua interpreter.

# But what that flag does?
Nelua can compile back to Lua, removing the type notations, one could use this do have a Lua with type notations, something similar [Teal](https://github.com/teal-language/tl) is doing, this is some hidden feature not much maintained and about to be deprecated somewhat in the future in favor of simplicity. That flag tells which is the target Lua version when compiling back to Lua, mainly to know if can use the recent Lua bitwise operators or not.

In the first days of the Nelua compiler I made it parse hundreds of Lua files and compile back to Lua removing all the type notations, and checked the output, this was an important step to make the language syntax/parser/code generator more stable, but can probably be deprecated someday.

**Comment by Andre-LA** [comment]
That makes sense, thanks :)
