### ISSUE TITLE
Code generation on recursive records + mipairs()

### ISSUE THREAD

**Issue by nateupstairs** [edubart/nelua-lang#191]
### Issue with code generation on recursive types

I ran into this in a small project and worked through to a result on discord, but realized I should probably propagate this here for a more official bug report.

It would seem as though a recursive record, if used as part of a mipairs iteration afterword, will create an incomplete type where "Nelua and C disagree on type size or align". I'm not sure of the details, but my guess is that the recursive nature of the data type added to mipairs is triggering some form of auto-detected reference type. It's pretty easy to reproduce.

### Code example

```lua
local vector = require 'vector'
require 'iterators'

local MyRec = @record{
  testing: boolean,
  children: vector(MyRec),
}

local data: MyRec = {
  testing = true,
  children = {
    { testing = false },
    { testing = true },
  }
}

for i, v in mipairs(data.children) do
  print(i, v)
end
```

### Expected behavior

I would expect this to print out the keys/values in mipairs.

### Workaround

Simply swapping mipairs for ipairs clears up the error immediately.

### Environment

Provide relevant information about your environment:
 - Nelua version : Nelua 0.2.0-dev : 23f1872e88c52e322f1dfe9058fb1a882b51b1a7
 - Platform : windows
 - Architecture e.g. x86_64
 - gcc version 12.1.0 MinGW-W64 x86_64-posix-seh

**Comment by edubart** [comment]
This is indeed a edge case bug due to use of recursive of records. I've provided a quick fix for this issue, and it should fix the error for the example you showed.
