### ISSUE TITLE
`--no-color` doesn't makes error report uncolored

### ISSUE THREAD

**Issue by Andre-LA** [edubart/nelua-lang#192]
### Bug description

By default, Nelua uses colors on error reporting, when using `--no-color` flag though, the color it's still used.

### Code example

```lua
pprint 'hello world'
```

### Expected behavior

Expected "error" as a normal text, without using the red color.

### Workaround

* Open [configer.lua at line 61](https://github.com/edubart/nelua-lang/blob/master/lualib/nelua/configer.lua#L61) file;
* Change `config` to `conf`
* Reinstall nelua

```diff
- if config.no_color then -- disable console coloring
+ if conf.no_color then -- disable console coloring
```

### Environment
 - Nelua version: `0.2.0-dev.1528+112409b9`
 - Platform: Pop!_OS 22.04 (Ubuntu)
 - Architecture: x86_64

**Comment by edubart** [comment]
Thanks for reporting, fixed in https://github.com/edubart/nelua-lang/commit/9de66a3c980c625448a8a85c71a059cb9ae3542b
