### ISSUE TITLE
Easier access to compiler endianness

### ISSUE THREAD

**Issue by IcedQuinn** [edubart/nelua-lang#206]
Access to whether the compiler is on a big or little endian system is useful for some bit operations.

For example in the xxhash algorithm in Nim:
```nim
proc XXH_readLE32(p: pointer): uint32 =
    when cpu_endian == little_endian:
        return XXH_read32(p)
    else:
        return XXH_swap32(XXH_read32(p))
```

I searched for `endian` in the documentation search engine and with silver searcher in the codebase. It looks like `cdefs.lua` does mention some endian checking but the docs don't mention it.

**Comment by edubart** [comment]
You can check for this like in the example:

```lua
## if ccinfo.is_little_endian then
  print 'little endian'
## elseif ccinfo.is_big_endian then
  print 'big endian'
## else
  print 'endianess is unknown'
## end
```
