### ISSUE TITLE
Nelua org for transferring repo

### ISSUE THREAD

**Issue by stefanos82** [edubart/nelua-lang#212]
@edubart can you enable the nelua org so I can transfer `nelua.vim` repo?

I cannot delete my GitHub account if I don't transfer the repository elsewhere first.

**Comment by edubart** [comment]
I don't really use Nelua org in GitHub, however I do own it to avoid someone taking it over. I was trying to fork it to my own account, but sadly Github is giving me errors, I will wait a day or two and hopefully Github will fix the issue and then try to fork it again. In case your account vanishes, I have a personal clone of the repository that I can push.

**Comment by stefanos82** [comment]
Perfect! Time to delete my account then; I will be keeping an eye on Nelua, but from a distance and if I find something interesting to report, I will send you an email and hopefully you will receive it, as I have already done last night with no luck.

Keep up the good work!

**Comment by edubart** [comment]
The Nelua Vim plugin was moved to https://github.com/edubart/nelua-vim
