### ISSUE TITLE
Typo: macro example code doesn't use its parameter

### ISSUE THREAD

**Issue by RayMPerry** [edubart/nelua-lang#214]
![Screenshot](https://cdn.discordapp.com/attachments/827000766643437650/1105110740752404540/Screenshot_2023-05-08_at_07.32.04.png)

### Expected behavior
`str` should be used instead of the string literal 'hello'.

### Workaround
This works as intended if you write it with the parameter. This is just a typo.

```lua
##[[
-- create a macro that injects a custom node when called
local function print_macro(str)
  local node = aster.Call{{aster.String{str}}, aster.Id{"print"}}
  -- inject the node where this macro is being called from
  inject_astnode(node)
end
]]

## print_macro('hello (again)')
```

Output:
```lua
print('hello (again)')
```

**Comment by edubart** [comment]
Fixed.
