### ISSUE TITLE
support windows msvc cl compiler

### ISSUE THREAD

**Issue by zeromake** [edubart/nelua-lang#224]
### Feature motivation

I want to use MSVC on Windows 

### Code example

on [my fork](https://github.com/zeromake/nelua-lang/commit/0943670e2f6d0a90e06c5373fc5489cebe4224bb) already achieved

```bat
> "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
> .\nelua.bat --verbose examples\fibonacci.nelua
generated ~\.cache\nelua\fibonacci.c
cl -nologo /utf-8 /EHsc /Zi /Fe"~\.cache\nelua\fibonacci.exe" "~\.cache\nelua\fibonacci.c"
fibonacci.c
C:\Users\ljh\.cache\nelua\fibonacci.exe
55
55
55
55
```
I would have liked to come up with a PR, after carefully reading the PR description decision, let's mention an issue first
If you don't feel the need msvc support(nelua some generate c code unable to compile), just turn close this issue.

**Comment by edubart** [comment]
You should try using MSVC Clang if that is an option for you. Then you don't need to do anything. I am afraid the `cl` compiler doesn't support all features Nelua need, you could check by running the test suite. Nelua may occasionally generate C code using extensions such as https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html that only GCC/Clang supports. (See also https://github.com/edubart/nelua-lang/discussions/73)

That is interesting, but not sure if I want to add that officially, unless everything is working good. I really want to encourage just using the Clang/GCC frontend.

**Comment by zeromake** [comment]
@edubart 
[Statement-Exprs](https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html) are more problems, need to redo cgenerator, I'll close this issue.
