### ISSUE TITLE
C code tries to initialize nltype with 0 in strange errorhandling / assert / module interaction

### ISSUE THREAD

**Issue by jrfondren** [edubart/nelua-lang#230]
### Bug description

This is a warning with gcc, and an error with tcc. I found it naturally while using nester to test a module that used utf8.codepoint()

### Code example

with modcheck.nelua:
```lua
require 'errorhandling'
local M = @record{}
local function f() assert(true) return 1 end
local x = f()
function M.f() return f() end
return M
```
You can observe the error with:
```
$ nelua -C -i 'require("modcheck")'
warning: using error handling module, it is highly experimental and incomplete!
/home/jfondren/.cache/nelua/eval_2jNUNGZEoYm.c: In function ‘nelua_require_modcheck’:
/home/jfondren/.cache/nelua/eval_2jNUNGZEoYm.c:2205:23: warning: excess elements in struct initializer
 2205 |       return (nltype){0};
      |                       ^
/home/jfondren/.cache/nelua/eval_2jNUNGZEoYm.c:2205:23: note: (near initialization for ‘(anonymous)’)
```
Where the larger context is
```c
nltype nelua_require_modcheck(nlniltype modname) {
  ({
    int64_t __callret = modcheck_f();
    if(nelua_error_status) {
      return (nltype){0};
    }   
    __callret;
  });
  return NELUA_NIL;
}
```

### Environment

x86_64 linux
Nelua 0.2.0-dev
Build number: 1588
Git date: 2023-09-16 16:20:44 -0300
Git hash: 596fcca5c77932da8a07c249de59a9dff3099495
Semantic version: 0.2.0-dev.1588+596fcca5
Copyright (C) 2019-2022 Eduardo Bart (https://nelua.io/)

**Comment by edubart** [comment]
Error handling module is not finished, it is full of issues. Maybe I should remove from standard library or leave in an experimental folder.

**Comment by jrfondren** [comment]
I wasn't using 'errorhandling' directly, I was using nester from nelua-batteries.

**Comment by edubart** [comment]
Fixed in https://github.com/edubart/nelua-lang/commit/decf713ca4bfd99b7bb9ae3c5f66b87761fd8621
