### ISSUE TITLE
Reassigned 'auto' parameter, inferred to have type 'nilptr', compiles to assignment to NULL

### ISSUE THREAD

**Issue by jrfondren** [edubart/nelua-lang#231]
### Code example

```lua
local function chars(s: string, state: auto)
  local stop = false
  for i=1, #s do
    stop, state = false, nilptr
  end
end

chars('abc', nilptr)
```

### Current behavior

```
$ nelua nullasgn2.nelua
/home/jfondren/.cache/nelua/nullasgn2.c: In function ‘nullasgn2_chars_1’:
/home/jfondren/.cache/nelua/nullasgn2.c:98:10: error: lvalue required as left operand of assignment
   98 |     NULL = _asgntmp_2;
      |          ^
error: C compilation for '/home/jfondren/.cache/nelua/nullasgn2' failed
```

### Another example

This results in a compilation to `NULL = NULL;`

```lua
local function chars(s: string, state: auto)
  for i=1, #s do
    state = nilptr
  end
end

chars('abc', nilptr)
```

### Workaround

Almost any change will result in working code or a clean error from Nelua instead of this error from C. Giving `state` an explicit stop, or assigning something other than `nilptr`. In this example, `nil` also works. The error was naturally arrived at by

1. demonstrating iteration with higher order functions, which requires explicit handling of state
2. using an example where the explicitly-handled state wasn't actually needed
3. considering `nilptr` to be a reasonable "don't care" value.

### Environment

x86_64 linux
Nelua 0.2.0-dev
Build number: 1588
Git date: 2023-09-16 16:20:44 -0300
Git hash: 596fcca5c77932da8a07c249de59a9dff3099495
Semantic version: 0.2.0-dev.1588+596fcca5
Copyright (C) 2019-2022 Eduardo Bart (https://nelua.io/)

**Comment by stefanos82** [comment]
In Overview documentation, in Pointer section we can read

```lua
local n = nilptr -- a generic pointer, initialized to nilptr
local p: pointer -- a generic pointer to anything, initialized to nilptr
local i: *integer -- pointer to an integer
```

which in other words, what your code is actually doing is indeed trying to assign `NULL` inside `NULL`; but if you replace your `auto` to `pointer`, it compiles as expected.

This is the generated C code with the usage of `auto`:

```c
static void tmp_chars_1(nlstring s, void* state);
static int nelua_main(int argc, char** argv);
/* ------------------------------ DEFINITIONS ------------------------------- */
void tmp_chars_1(nlstring s, void* state) {
  for(intptr_t i = 1, _end = ((intptr_t)(s).size); i <= _end; i += 1) {
    NULL = NULL;
  }
}
```

and this is with the usage of `pointer` instead:

```c
static void tmp_chars(nlstring s, void* state);
static int nelua_main(int argc, char** argv);
/* ------------------------------ DEFINITIONS ------------------------------- */
void tmp_chars(nlstring s, void* state) {
  for(intptr_t i = 1, _end = ((intptr_t)(s).size); i <= _end; i += 1) {
    state = (void*)NULL;
  }
}
```

When I read your code I said to myself: "wait, isn't `state` going to become `nilptr` and you want to assign `nilptr` in it? Is this even allowed?" and decided to run the aforementioned tests.

**Comment by stefanos82** [comment]
Hmm...yes, you have a point :thinking:

**Comment by stefanos82** [comment]
So, after some further investigation, it seems like that indeed `nilptr` is an `rvalue`, it's not a type; its type should be `pointer`.

What helped me realized this was the flag `--print-analyzed-ast`.

```
Call {
        attr = {
          calleesym = "tellmemytype: function(x: nilptr): void",
          calleetype = "function(x: nilptr): void",
          polyeval = "table: 0x7f5114df7a00",
          pseudoargattrs = "table: 0x7f5114dfae40",
          pseudoargtypes = "table: 0x7f5114dfae00",
          type = "void",
        },
        {
          Nilptr {
            attr = {
              comptime = true,
              type = "nilptr",
            },
          }
        },
       ...
```

**Comment by edubart** [comment]
Fixed in https://github.com/edubart/nelua-lang/commit/a60b9fe2a5092fbb4ee7fd4541440fccccbcb6e2

**Comment by stefanos82** [comment]
@edubart I have just tested this commit and the generated C code for definition looks like this:

```c
void tmp_chars_1(nlstring s, void* state) {
  bool stop = false;
  for(intptr_t i = 1, _end = ((intptr_t)(s).size); i <= _end; i += 1) {
    bool _asgntmp_1 = false;
    stop = _asgntmp_1;
  }
}
```

Excuse my ignorance, but shouldn't the aforementioned code look something like

```c
void tmp_chars_1(nlstring s, void* state) {
  bool stop = false;
  for(intptr_t i = 1, _end = ((intptr_t)(s).size); i <= _end; i += 1) {
    bool _asgntmp_1 = false;
    stop = _asgntmp_1;
    state = (void *) NULL;
  }
}
```

**Comment by jrfondren** [comment]
Pass some other pointers. The function that doesn't assign `state` to NULL is the one that's specialized to `state` already being NULL.

**Comment by stefanos82** [comment]
> Pass some other pointers. The function that doesn't assign `state` to NULL is the one that's specialized to `state` already being NULL.

In other words, in

```lua
local function chars(s: string, state: auto)
  local stop = false
  for i=1, #s do
    stop, state = false, nilptr
  end
end

chars('abc', nilptr)
```

because we pass a `nilptr` in `chars()`, the compiler gets informed to ignore the `,nilptr` part from the `for` loop?

**Comment by edubart** [comment]
> because we pass a `nilptr` in `chars()`, the compiler gets informed to ignore the `,nilptr` part from the `for` loop?

Correct, the thing is already `nilptr`, so the compiler eliminates the code.

**Comment by stefanos82** [comment]
...wait, you have applied Dead Code Elimination **in AST** mechanism, before emitting C code?! Bruh! O.o
