### ISSUE TITLE
Invalid unitname generated for directories that look like numeric literals

### ISSUE THREAD

**Issue by jrfondren** [edubart/nelua-lang#240]
### Code example

```lua
local function f() <nodce> end
```
When compiled in a directory named '001-example', an invalid unitname is generated:
```
$ nelua 001-example/test.nelua
/home/jfondren/.cache/nelua/test.c:79:13: error: invalid suffix "_example_test_f" on integer constant
   79 | static void 001_example_test_f(void);
      |             ^~~~~~~~~~~~~~~~~~
/home/jfondren/.cache/nelua/test.c:79:13: error: expected identifier or ‘(’ before numeric constant
/home/jfondren/.cache/nelua/test.c:81:6: error: invalid suffix "_example_test_f" on integer constant
   81 | void 001_example_test_f(void) {
      |      ^~~~~~~~~~~~~~~~~~
/home/jfondren/.cache/nelua/test.c:81:6: error: expected identifier or ‘(’ before numeric constant
error: C compilation for '/home/jfondren/.cache/nelua/test' failed
```

### Expected behavior

I expected a unitname like XXX_example, as is done with non-Latin characters.

### Workaround

Files can set an explicit unitname with
```lua
## pragmas.unitname = 'X001_example'
```

### Environment

x86_64 linux
Nelua 0.2.0-dev
Build number: 1605
Git date: 2023-11-05 16:12:59 -0300
Git hash: decf713ca4bfd99b7bb9ae3c5f66b87761fd8621
Semantic version: 0.2.0-dev.1605+decf713c
Copyright (C) 2019-2023 Eduardo Bart (https://nelua.io/)

**Comment by stefanos82** [comment]
Can you provide a full demo to check it on my side? I have tested the code excerpt you shared and could not reproduce the behavior you shared above.

**Comment by edubart** [comment]
Thanks for reporting, fixed in https://github.com/edubart/nelua-lang/commit/0d8eaf423baa533f59504e425532f47c3cb90577
