### ISSUE TITLE
Compatible with Lua C plug-in

### ISSUE THREAD

**Issue by acodervic** [edubart/nelua-lang#252]
Compatible with Lua C plug-in? The target of nelua is C, but currently there are not enough libraries to use nelua. It is very difficult to promote nelua, especially for novices who are not proficient in c/c++. Is it possible to use some method to utilize lua c ready-made plug-in ecosystem, which will be a major advantage of nelua

**Comment by stefanos82** [comment]
You mean this? https://github.com/edubart/nelua-batteries

**Comment by acodervic** [comment]
> You mean this? https://github.com/edubart/nelua-batteries

Thank you !
