### ISSUE TITLE
Nelua filename with numeric prefix results in a compile error

### ISSUE THREAD

**Issue by winrg** [edubart/nelua-lang#271]
### Bug description

The compiler's prefixing scheme for files in individual code units doesn't handle certain filenames properly. Compiling `1.nelua` will fail, if the file contains any variable or function definitions.

### Expected behavior

The prefixing could have some scheme for escaping numbers consistently, but it would need to ensure that that wouldn't collide with a different file.

### Workaround

There's a pragma that can fix this:

```lua
## pragmas.unitprefix = 'any_string_that_doesnt_start_with_a_number'
```

**Comment by edubart** [comment]
This is known, it is the same as https://github.com/edubart/nelua-lang/issues/240

**Comment by edubart** [comment]
Thanks for reporting, fixed in https://github.com/edubart/nelua-lang/commit/0d8eaf423baa533f59504e425532f47c3cb90577
