### ISSUE TITLE
Piping into nelua cli

### ISSUE THREAD

**Issue by kmafeni04** [edubart/nelua-lang#273]
**WARNING: Please, read this note carefully before submitting a feature request:**

It is important to realize that **this is NOT A SUPPORT FORUM**, this is for ISSUES ONLY.

If you need support, have questions, ideas to discuss you should use
the [Nelua Discussions](https://github.com/edubart/nelua-lang/discussions) forum or
the [Nelua Discord server](https://discord.gg/7aaGeG7).

Please, before submitting a new issue, verify the following:
 - You have tested it on latest Nelua version from master branch.
 - You have checked that there is no similar feature already implemented or requested.

---

### Feature motivation
I am currently trying to write my own lsp in nelua and discovered I couldn't just send the output of the current file to nelua to analyze

### Feature description
The ability to pipe the output of a command to be run by nelua

### Code example
Lua example:
```sh
echo "local x = 1;print(x)" | lua
1
```

### Describe alternatives you've considered
The work around I've found is to create a temporary file and analyze that then delete it but creating a file on every lsp request is rather slow

```lua
local tmp_file_name = os.tmpname()
local tmp_file = io.open(tmp_file_name, "w")
tmp_file:write(current_file)
local ast_prog = io.popen("nelua -a " .. tmp_file_name .. " 2>&1")
-- My actual logic
tmp_file:close()
ast_prog:close()
```

**Comment by cattokomo** [comment]
Is this a really serious issue? You can always just create a temporary file and then pass it into the compiler.

**Comment by kmafeni04** [comment]
It's nothing major or more of just a request, if it's deemed unnecessary, I'll close but I'd rather ask than assume no from the beginning

**Comment by mbekkomo** [comment]
You can leave it here, as it's just an improvement over the CLI capabilities.

**Comment by edubart** [comment]
Actually this has been supported for a long time, but to be fair the help was not saying anything about it. You can do this passing `-` as the input, like this:

```sh
$ echo 'print(_VERSION)' | nelua -
Nelua 0.2.0-dev
```

I improved the help in https://github.com/edubart/nelua-lang/commit/038c45f19842d7b18c32b6b4f7e631e15d77d453 so, Nelua `--help` shows:

```
Arguments:
  input                     Input source file
                            Use '-' to read from stdin
```
