### ISSUE TITLE
Can't use filenames starting with digits

### ISSUE THREAD

**Issue by sls1005** [edubart/nelua-lang#276]
### Bug description

If the name of the input file starts with an ASCII digit, it will lead to a C compiler error, as the generated C variable names will be prefixed with the file name, and a name that starts with a digit is not a valid C identifier.

### Code example

*(None)*

### Expected behavior

No C compiler error.

### Workaround

* Don't use file names that start with digits.

#### Other solutions

* Forbid these names (by checking for them).

* Use an alphabet or an underscore to prefix variables.

### Environment

 - Nelua version: 0.2.0-dev
 - Platform: Android 14, with Termux
 - Architecture: AArch64
 - C compiler: Clang 19.1.2

**Comment by mbekkomo** [comment]
Duplicate of #271, already fixed in commit https://github.com/edubart/nelua-lang/commit/0d8eaf423baa533f59504e425532f47c3cb90577.

**Comment by sls1005** [comment]
I see.
