### ISSUE TITLE
Consistent increase in memory usage when calling visitors.x functions

### ISSUE THREAD

**Issue by kmafeni04** [edubart/nelua-lang#282]
**WARNING: Please, read this note carefully before submitting a new bug:**

It is important to realize that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS ONLY.

If you need support, have questions, ideas to discuss you should use
the [Nelua Discussions](https://github.com/edubart/nelua-lang/discussions) forum or
the [Nelua Discord server](https://discord.gg/7aaGeG7).

Please, before submitting a new issue, verify the following:
 - You have tested it on latest Nelua version from master branch.
 - You have checked that there is no similar issue already reported.
 - You have checked that your code has no errors or misuse of Nelua.

---

### Bug description
I am currently working on an (lsp)[https://github.com/kmafeni04/nelua-lsp] for the language and I have come across an issue where if I call
```lua
local ok, err = except.trycall(function()
  ast = aster.parse(current_file, current_file_path)
  -- logger.log(ast)
  local context = AnalyzerContext(analyzer.visitors, ast, generator)
  except.try(function()
    for _, v in pairs(typedefs.primtypes) do
      if v.metafields then
        v.metafields = {}
      end
    end

    context = analyzer.analyze(context)
  end, function(e)
    e.message = ("%s%s"):format(context:get_visiting_traceback(1), e:get_message())
  end)
end)
```
The memory usage continues to increase until it locks my system
Upon further digging, I discovered the context:traverse_nodes function which further calls a visitors.x function, x being it's tag

```lua
function AnalyzerContext:traverse_node(node, ...)
  local done = node.done
  if done then
    return done ~= true and done or nil
  end
  -- bench_traverse(self, node)
  local nodestack = self.nodestack
  local index = #nodestack+1
  nodestack[index] = node -- push node
  local ret = self.visitors[node.tag](self, node, ...)
  nodestack[index] = nil -- pop node
  return ret
end
```
From here, I was unable to determine whether it was one particular function causing the issue but I do believe it has to do with the garbage collecter being unable to free memory because of the ast. This may not be an issue on one time compilations but on frequent requests in a single process, significant memory usage occurs in a very short span of time

### Code example
none
### Expected behavior
Not to increase memory usage on each call
### Workaround
none
### Environment

Provide relevant information about your environment:
 - Nelua version (0.2.0-dev)
 - Platform (Arch Linux)
 - Architecture (x86_64)

**Comment by edubart** [comment]
Can you share a minimal Lua script reproducing the issue? It would help me to debug this.

Could try calling `collectgarbage()` sporadically if you think the GC is not running. Parsing an AST and analyzing a context generates a lot of garbage, and usually should be freed when the collector runs, unless there is some reference being retained somewhere in your code (or in the Nelua compiler).

In any case, I have came up with the following script:

```lua
local aster = require('nelua.aster')
local AnalyzerContext = require 'nelua.analyzercontext'
local except = require 'nelua.utils.except'
local fs = require 'nelua.utils.fs'

for i=1,100 do
  local ok, err = except.trycall(function()
    ast = aster.parse(fs.readfile('test.nelua'), 'test')
    -- logger.log(ast)
    local context = AnalyzerContext(analyzer.visitors, ast, generator)
    except.try(function()
      for _, v in pairs(typedefs.primtypes) do
        if v.metafields then
          v.metafields = {}
        end
      end

      context = analyzer.analyze(context)
    end, function(e)
      e.message = ("%s%s"):format(context:get_visiting_traceback(1), e:get_message())
    end)
  end)
  collectgarbage()
  print('mem', collectgarbage("count"))
end
```

Which doesn't seem to have any memory leaking, because it stays constant:

```
96	mem	1176.9931640625
97	mem	1176.9931640625
98	mem	1176.9931640625
99	mem	1176.9931640625
100	mem	1176.9931640625
```

Removing `collectgarabge()`, you will see some noise, because garbage is collected at random times:
```
96	mem	1420.7978515625
97	mem	1526.419921875
98	mem	1632.041015625
99	mem	1442.93359375
100	mem	1548.5537109375
```

But usually stays low. In any case, I highly recommend explicitly running `collectgarbage()` after every parse + analyze combo, because this generates a lot of trash references. Compiling in general is known to be a task that generates a lot of garbage temporarily, in fact some compilers prefer to disable the GC before parse + analyze, and when it finishes it does a manual full garbage collection cycle.

Look now what happen if you retain the references in a temporary variable, by saving both `context` and `ast` in a global table in this code:

```lua
local aster = require('nelua.aster')
local AnalyzerContext = require 'nelua.analyzercontext'
local except = require 'nelua.utils.except'
local fs = require 'nelua.utils.fs'

local references = {}
for i=1,100 do
  local ok, err = except.trycall(function()
    ast = aster.parse(fs.readfile('test.nelua'), 'test')
    table.insert(references, ast)
    -- logger.log(ast)
    local context = AnalyzerContext(analyzer.visitors, ast, generator)
    except.try(function()
      for _, v in pairs(typedefs.primtypes) do
        if v.metafields then
          v.metafields = {}
        end
      end

      context = analyzer.analyze(context)
      table.insert(references, context)
    end, function(e)
      e.message = ("%s%s"):format(context:get_visiting_traceback(1), e:get_message())
    end)
  end)
  collectgarbage()
  print(i, 'mem', collectgarbage("count"))
end
```

```lua
1	mem	1265.859375
...
28	mem	2197.4658203125
29	mem	2235.23046875
30	mem	2272.9951171875
31	mem	2310.759765625
32	mem	2348.5244140625
...
97	mem	4804.7265625
98	mem	4842.4912109375
99	mem	4880.255859375
100	mem	4918.0205078125
```

See, the memory will keep growing.

**Comment by edubart** [comment]
Also worth mentioning that as a compiler, Nelua changes Lua's default garbage collector, to be more lazy, and only collect roughly when memory grows 8x, this is an optimization. This is done in `runner.lua`:

```
if _VERSION == 'Lua 5.4' then
  collectgarbage("incremental", 800, 400, 16)
end
```

So just requiring `runner.lua` will change the garbage collector default behavior,  if you use this file, it could be affecting your code. So you could try tuning the garbage collector after requiring this file.

Actually, the example above with this file required and no collectgarbage calls, generates the following:

```
86	mem	10094.87109375
87	mem	10200.4921875
88	mem	10306.112304688
89	mem	10411.734375
90	mem	10517.353515625
91	mem	10622.975585938
92	mem	10728.59765625
93	mem	10834.21875
94	mem	10939.836914062
95	mem	11045.458984375
96	mem	11183.081054688
97	mem	11288.703125
98	mem	11394.322265625
99	mem	11499.944335938
100	mem	11605.56640625
```

Looks like the memory is growing forever, but it's not really, eventually it will collect, it is just being very lazy and delaying the collect cycle.

**Comment by kmafeni04** [comment]
> Can you share a minimal Lua script reproducing the issue? It would help me to debug this.

```lua
local except = require("nelua.utils.except")
local analyzer = require("nelua.analyzer")
local typedefs = require("nelua.typedefs")
local AnalyzerContext = require("nelua.analyzercontext")
local aster = require("nelua.aster")
local generator = require("nelua.cgenerator")

local function analyze_ast(current_file, current_file_path)
  local ast
  local ok, err = except.trycall(function()
    ast = aster.parse(current_file, current_file_path)
    -- logger.log(ast)
    local context = AnalyzerContext(analyzer.visitors, ast, generator)
    except.try(function()
      for _, v in pairs(typedefs.primtypes) do
        if v.metafields then
          v.metafields = {}
        end
      end

      context = analyzer.analyze(context)
    end, function(e)
      e.message = ("%s%s"):format(context:get_visiting_traceback(1), e:get_message())
    end)
  end)
end

local current_file = [[
require 'hashmap'
require 'io'
require 'os'
require 'arg'
require 'traits'

local optional = facultative

local Option = @record{
  opt_short: string,
  opt_desc: string,
  opt_default: string,
}

local Argparse = @record{
  name: string,
  desc: string,
  epilog: string,
  options: hashmap(string, Option),
  args: hashmap(string, string)
}

function Argparse.new(name: optional(string), desc: optional(string), epilog: optional(string)): Argparse
  local parser: Argparse
  ## if name.type.is_string then
    parser.name = name
  ## end
  ## if desc.type.is_string then
    parser.desc = desc
  ## end
  ## if epilog.type.is_string then
    parser.epilog = epilog
  ## end
  return parser
end
  
]]
local current_file_path = "/home/user/Desktop/test.nelua"

while true do
  analyze_ast(current_file, current_file_path)
  os.execute("sleep 2s")
end
```

https://github.com/user-attachments/assets/54c5f4b3-3506-4bd8-b2dd-9992a1bbb5ac

**Comment by edubart** [comment]
I was able to reproduce, thanks for the code, I will investigate and try to fix this.

**Comment by edubart** [comment]
Fixed this issue in https://github.com/edubart/nelua-lang/commit/a69a12d1e1e5ee0bfab299350e5d707ff7b2e744
Also you don't need anymore to do:

```lua
      for _, v in pairs(typedefs.primtypes) do
        if v.metafields then
          v.metafields = {}
        end
      end
```
