### ISSUE TITLE
Creating a C library ?

### ISSUE THREAD

**Issue by linkpy** [edubart/nelua-lang#30]
The "Overview" section on Nelua website says :

> You can use Nelua to create C libraries, when doing this you may want to fix the name of the generated C function and export it:

It shows a code example, but i'm unable to find how to actually generate that library.
Doing `nelua --help` doesn't show any options regarding that and the documentation doesn't show any options to enable for this.

Thanks

**Comment by edubart** [comment]
Yea docs for that is missing, I will work on an example for that in a repository soon, then I will share here.

**Comment by edubart** [comment]
I've added a test as an example how to make a C library. Exporting and importing C symbols. The code is commented for explaining the used directives.

This is the library source code exporting C symbols:
https://github.com/edubart/nelua-lang/blob/master/tests/mylib_test.nelua

This an example using that library and importing its C symbols:
https://github.com/edubart/nelua-lang/blob/master/tests/libmylib.nelua

You can run the example if you clone this repository and run the following commands:

```bash
nelua -o libmylib tests/libmylib.nelua
nelua -o mylib.nelua tests/mylib_test.nelua
```

For reference, this is the output in my computer:
```
➜  nelua-lang git:(master ✓) nelua -o libmylib tests/libmylib.nelua 
generated /home/bart/projects/nelua/nelua-lang/nelua_cache/tests/libmylib.c
gcc -o "libmylib.so" "~/nelua-lang/nelua_cache/tests/libmylib.c" -Wall -lm -fwrapv -g -Wextra -Werror -shared -fPIC
library compiled!
➜  nelua-lang git:(master ✓) nelua -o mylib_test tests/mylib_test.nelua 
generated /home/bart/projects/nelua/nelua-lang/nelua_cache/tests/mylib_test.c
gcc -o "mylib_test" "~/nelua-lang/nelua_cache/tests/mylib_test.c" -Wall -lm -fwrapv -g -Wextra -Werror -L. -Wl,-rpath,'$ORIGIN' -lmylib
/home/bart/projects/nelua/nelua-lang/mylib_test 
mylib - init
mylib - in top scope
mylib - sum
the sum is:
3
mylib - terminate
```

I've tested only in my Linux, but it should work on MSYS2 + MinGW on Windows also.

**Comment by linkpy** [comment]
The version I had did not have the `-o` options, I pull and recompiled the compiler. You should also add the compilation commands in the files directly as comments, so people can find them there too.

`mylib_test.nelua` doesn't compile on my end (Windows 10, MSYS2 Mingw64) :

```
$ nelua -o libmylib libmylib.nelua
generated nelua_cache\libmylib.c
gcc -o "libmylib.dll" "nelua_cache\libmylib.c" -Wall -lm -fwrapv -g -shared -fPIC
library compiled!

$ nelua -o mylib_test mylib_test.nelua
generated nelua_cache\mylib_test.c
gcc -o "mylib_test.exe" "nelua_cache\mylib_test.c" -Wall -lm -fwrapv -g -L. -Wl,-rpath,'$ORIGIN' -lmylib
C compilation for 'mylib_test.exe' failed:
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccOF23PZ.o: in function `nelua_main':
C:\msys64\home\linkie-pi\nelua-lsp/nelua_cache/mylib_test.c:87: undefined reference to `mylib_init'
collect2.exe: error: ld returned 1 exit status
```

The cached C file has the cexports, except for `mylib_init` :

```c
nelua_cexport int64_t mylib_sum(int64_t x, int64_t y);
void mylib_init();
nelua_cexport void mylib_terminate();
```

Adding `cexport` to the init function fixes it.

**Comment by edubart** [comment]
I've added the `-o` in last commit, I never needed it until this example, and I tend to add stuff the first time is needed.

> Adding cexport to the init function fixes it.

This for noticing! I will patch this, it worked here because I'm on linux. Everything worked fine there on Windows with this change? If you have more issues let me know so I go to my Windows machine and troubleshoot there.

**Comment by linkpy** [comment]
On windows, the code works correctly (once the <cexport> is added).
