### ISSUE TITLE
Cross-compilation for nelua???

### ISSUE THREAD

**Issue by rprata** [edubart/nelua-lang#37]
Hi, 

Is it possible to add support for cross-compilation? For example, we can set `toolchain`, `compiler version`, `rootfs` and other tools? It is a good feature for embedded system.

**Comment by edubart** [comment]
You just need to use a different C compiler or CFLAGS. I do this with `nelua --cc=x86_64-w64-mingw32-gcc helloworld.nelua` for example to cross compile to Windows while on Linux and `nelua --cc=emcc --cpu-bits=32 helloworld.nelua` to cross compile to WebAssembly. Usually any platform that supports C is supported.
