### ISSUE TITLE
C structs in record

### ISSUE THREAD

**Issue by AlectronikForge** [edubart/nelua-lang#39]
When writing C bindings, it's nice to be able to put the functions into a single record, e.g. Sdl.Init() instead of SDL_Init. But the compiler doesn't accept it to refactor structs the same way:

```lua
global Sdl.Event <cimport, cinclude'<SDL2/SDL.h>', nodecl> = @record {
  type: uint32,
  padding: [56]byte
}

function Sdl.PollEvent(event: *Sdl.Event): int32 <cimport, cinclude'<SDL2/SDL.h>', nodecl> end
```
leads to:

```
sdl.nelua:51:35: syntax error: unclosed parenthesis, did you forget a `)`?
function Sdl.PollEvent(event: *Sdl.Event): int32 <cimport, cinclude'<SDL2/SDL.h>', nodecl> end
                                  ^
```

**Comment by edubart** [comment]
Indeed, this is not supported yet, it is in the roadmap do be done in a module system like Lua. Right now use globals, I know this can be unconfortable for some, but note the language is in alpha and some features are not implemented yet.

**Comment by edubart** [comment]
Since commit https://github.com/edubart/nelua-lang/commit/8341b617e68c8a7c6ff49e77b5d1e2cace8c84fc this is possible!
For example, the following now works:

```lua
## linklib 'SDL2'

global Sdl = @record{}

global Sdl.Event <cimport'SDL_Event', cinclude'<SDL2/SDL.h>', nodecl> = @record {
  type: uint32,
  padding: [56]byte
}

function Sdl.PollEvent(event: *Sdl.Event): int32 <cimport'SDL_PollEvent', cinclude'<SDL2/SDL.h>', nodecl> end

local e: Sdl.Event
Sdl.PollEvent(&e)
```
