### ISSUE TITLE
The operator bitwise not isn't working:

### ISSUE THREAD

**Issue by Andre-LA** [edubart/nelua-lang#4]
Hello :)

I installed it yesterday through luarocks, I've been testing it and found that ``~0`` (or any other number) triggers an error:

```lua 
local x = ~10
```

```
$ nelua bnot_test.nelua 
bnot_test.nelua:1:12: error: in unary operation `bnot`: invalid operation for type 'int64'
local x = ~10
           ^
```

(edit: typo)

**Comment by edubart** [comment]
Hello, thanks for notifying!
A lot is not implemented yet, but this one I really forgot in my TODO, will do it soon.

**Comment by edubart** [comment]
I've just fixed, remember that to test the changes you will need to reinstall again via luarocks.

**Comment by Andre-LA** [comment]
Thanks :D
