### ISSUE TITLE
Fork for microntrollers

### ISSUE THREAD

**Issue by rprata** [edubart/nelua-lang#42]
Hi maintainers, 

I've forked this project and I'm implementing support to develop applications for `Arduino Uno` using `nelua`. Is it good for the main project (I could create a pull request with my modifications) or is better to keep this fork separated of main repository (with a different name, but updated with upstream)?

**Comment by edubart** [comment]
I don't think a fork is need to improve support for Arduino, probably you want just to make a separate library and request features or potential fixes to improve the Nelua compiler usage with Arduino.
But you are free to fork and do whatever you want as the project is open source.

Regarding the pull requests, Nelua is not a language for any specific platforms, just like C/Lua isn't, so I probably wouldn't merge specific APIs/modules/tools for Arduino, as the language try to remain platform agnostic. But I would merge fixes and improved flexibility to make coding on platforms such as Arduino easier. In any case it would depend very much on the pull request.

**Comment by rprata** [comment]
@edubart , 
Thank you for your answer. I've tried to create a separate library for Arduino, but I didn't success. I needed to adjust some scripts:
- `nelua/cgenerator.lua`
- `nelua/runner.lua`

This changes were applied because Arduino Uno architecture  (8 bits)

So, is it possible to send my modifications for this context, not harming the project completely (creating a conditional for this context)?

**Comment by edubart** [comment]
@rprata I've made comments for workaround those changes that you made in your fork.

**Comment by rprata** [comment]
@edubart , thank you. I adjusting according your suggestions and I could revert my modifications. In this case I'll create a separeted library for arduino development.
