### ISSUE TITLE
return doesn't stop execution of an expression block

### ISSUE THREAD

**Issue by Andre-LA** [edubart/nelua-lang#48]
Please, before submitting a new issue verify and check:
 - [x] I tested it on latest Nelua version from master branch.
 - [x] I checked there is no similar issue already reported.
 - [x] My code has no errors or misuse of Nelua.

---

### Bug description

On an expression block, the expression evaluation should be done at a `return`.
However, there is a case where this doesn't happens.

### Code example
```lua
local x = (do
  if true then
    print "x is 10"
    return 10
  else
    print "x is 20"
    return 20
  end
  print "x is 30"
  return 30
end)

print "x evaluated, it should be 10"
print('x is', x)
assert(x == 10, 'x is not 10')
```

### Expected behavior

Expected output:
```
x is 10
x evaluated, it should be 10
x is	10
```

Output:
```
x is 10
x is 30
x evaluated, it should be 10
x is	30
x is not 10
```

### Environment

 - Nelua version is:
 ```
Nelua 0.2.0-dev
Build number: 808
Git date: 2020-12-27 14:57:30 -0300
Git hash: d44947ba5fef36fe0a8c25c3f04fa72d061f6bdb
```
 - Platform: Pop_OS! 20.10 (based on Ubuntu 20.10)

**Comment by edubart** [comment]
Fixed, thanks for the report!

**Comment by Andre-LA** [comment]
Thanks ^^
