### ISSUE TITLE
Nelua crashes when using calling a method and the function declaration doesn't contain any parameters

### ISSUE THREAD

**Issue by Andre-LA** [edubart/nelua-lang#56]
- [x] I tested it on latest Nelua version from master branch.
 - [x] I checked there is no similar issue already reported.
 - [x] My code has no errors or misuse of Nelua. (well, is a misuse actually)

---

### Bug description

When trying to use a method on variable which the type actually declares, but in this declaration there is no parameters, the Nelua compiler crashes and gives the compiler's traceback instead of giving an error message.

### Code example

```lua
local R = @record{a: integer}

function R.hello()
  print'hello'
end

local x: R = {}
x:hello()
```

This problem doesn't happens when the `:` syntax sugar is not used:

```lua
local R = @record{a: integer}

function R.hello()
  print'hello'
end

local x: R = {}
R.hello(x)
```
output:
```
 nelua ../teste.nelua 
../teste.nelua:8:8: error: in call of function 'R.hello': expected at most 0 arguments but got 1
R.hello(x)
       ^~~
```

### Expected behavior

An error message is expected, something like the output when not using the `:` syntax sugar.

### Environment

 - Nelua version: 
     - Nelua 0.2.0-dev
     - Build number: 866
     - Git date: 2021-02-05 16:35:19 -0300
     - Git hash: 3464918b723e1d7949b5fe7a50005b227c39da55
 - Platform (e.g. Windows/MSYS2, Ubuntu Linux, MacOS)
     - Pop!_OS 20.10 (Based on Ubuntu 20.10)

**Comment by edubart** [comment]
Fixed and added a test case for this in the spec, thanks for the report!
