### ISSUE TITLE
better type inference for facultative arguments

### ISSUE THREAD

**Issue by Andre-LA** [edubart/nelua-lang#63]
Please, before submitting a new feature verify and check:
 - [x] I tested it on latest Nelua version from master branch.
 - [x] I checked there is no similar feature already implemented or requested.
 - [x] I checked that the feature is not in the [roadmap](https://github.com/edubart/nelua-lang/projects).
---
### Feature motivation
When using facultatives, nelua recognize the argument as a `table` and not as the desired type, this is resolved using casting.

### Feature description
While is resolved using a cast, it would be nice if nelua could recognize the type without it. This feature can also be useful when the type is not accessible.

### Code example

```lua
local R = @record{a: integer, b: number}

local function hello(r: facultative(R))
  ## if not r.type.is_niltype then
    print("r is: ", r.a, r.b)
  ## else
    print("r is not given")
  ## end
end

hello()
hello({10, 20}) -- currently must be hello((@R){10, 20})
```

### Describe alternatives you've considered
Using casting and exposing the type when it would be not accessible.

**Comment by stefanos82** [comment]
For some reason it reminds me how C++'s move semantics work behind the scenes with `static_cast<>()`.; fascinating stuff!

**Comment by edubart** [comment]
This feature has been added. By refactoring some code, I found an easy way to do this.
