### ISSUE TITLE
arguments aren't visible when preprocessing function return when the return type is composed

### ISSUE THREAD

**Issue by Andre-LA** [edubart/nelua-lang#64]
- [x] I tested it on latest Nelua version from master branch.
 - [x] I checked there is no similar issue already reported.
 - [x] My code has no errors or misuse of Nelua.

---

### Bug description
Argument atrrs are visible when preprocessing a function return type, like as introduced on commit 5394c97, however, when the return type is composed, it get invisible, unless is 100% preprocessed.

### Code example
```lua
local A = 10

-- this works
local function x(t: type): #[types.PointerType(t.value)]#
  ## staticassert(t.value.is_integral)
  return &A
end
print('x:', x(@integer))

-- this doesn't
local function y(t: type): pointer(#[t.value]#)
  ## staticassert(t.value.is_scalar)
  return &A
end
print('y:', y(@integer))
```

### Expected behavior
Works just as with non-argument types:
```lua
local A: integer = 10

local function x(t: type): pointer(#[A.type]#)
  ## staticassert(t.value.is_integral)
  return &A
end
print('x:', x(@integer))
```

### Environment
 - Nelua version:
   - Nelua 0.2.0-dev 
   - Build number: 994
   - Git date: 2021-04-15 16:40:44 -0300
   - Git hash: 88f0bd0a595d834ea9064fdb2ecb0198860d223e
 - Platform
   - Pop!_OS 20.10 (Ubuntu 20.10)

**Comment by edubart** [comment]
Fixed, thanks for reporting!
