### ISSUE TITLE
segfault fault filestream:close()

### ISSUE THREAD

**Issue by bokunodev** [edubart/nelua-lang#65]
**WARNING: Please, read this note carefully before submitting a new bug:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS ONLY.

If you need support, have questions, ideas to discuss you should use
the [Nelua Discussions](https://github.com/edubart/nelua-lang/discussions) forum or
the [Nelua Discord server](https://discord.gg/7aaGeG7).

Please, before submitting a new issue verify and check:
 - [ ] I tested it on latest Nelua version from master branch.
 - [ ] I checked there is no similar issue already reported.
 - [ ] My code has no errors or misuse of Nelua.

---

### Bug description

i made a program to download something from internet `example.com`
and write it to a file. but its always `Segmentation fault (core dumped)`
when i call `filestream:close()`

### Code example

Provide minimal reproduction code to test the bug.
Please, format the code properly and try to keep it as simple as possible, just focusing on the experienced bug.
```lua
require "modules/curl/curl"
require "io"

print("open a file")
local s:string, i:integer
local file:filestream
file,s,i = io.open("example", "w+")
print(file,s,i)

local function write_func(ptr:cstring, size:csize, nmemb:csize, userdata:pointer):csize
	local b:boolean, s:string, i:integer
	b, s, i = file:write(ptr)
	print("write callback", b, s, i)
	return size*nmemb
end


local client:pointer = curl_easy_init()
curl_easy_setopt(client, CURLOPT_URL, "https://example.com")
curl_easy_setopt(client, CURLOPT_WRITEFUNCTION, write_func)
local response:CURLcode = curl_easy_perform(client)
print(file:flush())
print("closing tmpfile", file:close()) -- always segfault after printing text.
print("curl cleanup")
curl_easy_cleanup(client)


```

### Expected behavior

no error

### Environment

Provide relevant information about your environment:
 - Nelua version (you can check with `nelua -v`).
```
~ $ nelua --version
Nelua 0.2.0-dev
Build number: 1020
Git date: 2021-05-12 17:25:40 -0300
Git hash: e9de5bbeabd77e1c1b8099c3ab53eaabec1a1774
``` 

 - Platform (e.g. Windows/MSYS2, Ubuntu Linux, MacOS)
 Arch linux

 - C compiler if your bug has C compiler errors. (e.g. GCC 10.2, Clang 11)
```
~ $ gcc --version
gcc (GCC) 10.2.0
```

**Comment by bokunodev** [comment]
its weird, i cant replicate it anymore.

**Comment by edubart** [comment]
Actually it's an error over a mistake. You made a mistake by trying to close the same file twice, but I tested the code here, and it crashed with the wrong error, I will fix soon, so when this is mistake happens the user can recover from it.
