### ISSUE TITLE
how to use linklib ?

### ISSUE THREAD

**Issue by ffred** [edubart/nelua-lang#8]
Hello,
can you please tell me how is linklib used ?
for example in your snake sample, I found :  ## linklib 'SDL2'
what kind of file should I give to it ?
thanks

**Comment by edubart** [comment]
The `linklib 'mylib'` just pass the flag `-lmylib` to the C compiler, where and how your C compiler looks for libs depends on which C compiler you are using. For `SDL2` for example usually the GCC/Clang/MinGW compiler tries to find `libSDL2.a`, `libSDL2.so`, `SDL2.dll` (depends on your platform) in your compiler `lib` folder.

If your installation is missing SDL2, you should install it. In Windows with MSYS2 it can be installed with the command `pacman -S mingw-w64-sdl2`, on Ubuntu can be installed with `apt-get install libsdl2-dev`, on custom Windows installation with MinGW you would have to download binaries for SDL2 or compile yourself, SDL2 binaries is available for download in SDL2 official website.

**Comment by ffred** [comment]
ok, that's what I was thinking and I did try rapidly with SDL2.dll, but still got something like a "cannot find" (didn't remember exactly). probably didn't placed it well. will look more at it, thanks..

**Comment by ffred** [comment]
got it working, but I had to copy from the console the nelua linking (and failing) command and send it again after adding an "-L" option pointing to my SDL2 directory. didn't work if I just put it in the path.
it seems that I need to put it in one of my mingw-w64 subdirectories if I want it to work directly..

**Comment by edubart** [comment]
@ffred In this case you have some options:
* You could pass in the command line the path with `nelua --cflags="-L/some/path" examples/snakesdl.nelua"`
* You could add to the snakesdl file `## cflags '-L/some/path'`
* You could export the environment variables `CFLAGS="-L/some/path"` in your terminal, and subsequent calls to `nelua` will find it.
* You could install SDL files correctly inside your compiler (bin/lib/include files)
* Lastly you could create a `.neluacfg.lua` in the current working directory containing:
```lua
return {
  cflags = '-L/some/path'
}
```

**Comment by ffred** [comment]
wow, thanks for the detailed answer. I thank about all that but not at home right now. just trying a few things when in pause at work ;-)  so didn't have the time to search for the correct syntax yet..
so thanks you, will keep all that noted.
