### ISSUE TITLE
error: assignment of read-only variable ‘const_a’

### ISSUE THREAD

**Issue by stefanos82** [edubart/nelua-lang#80]
**WARNING: Please, read this note carefully before submitting a new bug:**

> It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS ONLY.

> If you need support, have questions, ideas to discuss you should use
> the [Nelua Discussions](https://github.com/edubart/nelua-lang/discussions) forum or
> the [Nelua Discord server](https://discord.gg/7aaGeG7).

Please, before submitting a new issue verify and check:
 - [x] I tested it on latest Nelua version from master branch.
 - [x] I checked there is no similar issue already reported.
 - [x] My code has no errors or misuse of Nelua.

---

### Bug description

> A clear and concise description of the bug you are experiencing.
> Tell what you were trying to do and what happened instead.

The latest commit f448b29674a399600d4f1b19cd74b273233b5b36 breaks the code below.

```
$ nelua const.nelua 
C compilation for 'nelua_cache/const' failed:
nelua_cache/const.c: In function ‘nelua_main’:
nelua_cache/const.c:53:11: error: assignment of read-only variable ‘const_a’
   53 |   const_a = const_x;
      |           ^

```

### Code example

> Provide minimal reproduction code to test the bug.
> Please, format the code properly and try to keep it as simple as possible, just focusing on the experienced bug.
```lua
local x <const> = 1
local a <const> = x
print(a) -- outputs: 1

-- uncommenting the following will trigger the compile error:
-- error: cannot assign a constant variable
-- a = 2

```

### Expected behavior

> A clear and concise description of what you expected to happen.

To see `1` as output

### Environment

> Provide relevant information about your environment:
> - Nelua version (you can check with `nelua -v`).

```
Nelua 0.2.0-dev
Build number: 1155
Git date: 2021-07-15 17:28:09 -0300
Git hash: f448b29674a399600d4f1b19cd74b273233b5b36
Copyright (C) 2019-2021 Eduardo Bart (https://nelua.io/)
```

> - Platform (e.g. Windows/MSYS2, Ubuntu Linux, MacOS)

```
OS: GNU / Linux Debian testing 64-bit
```

> - C compiler if your bug has C compiler errors. (e.g. GCC 10.2, Clang 11)

```
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 
```

**Comment by edubart** [comment]
Thanks for reporting! I've just fixed. In recent commits I've started to emit more `const` keyword in the C code generator and this happened. I've added your example to the test suite, so this regression should not happen again.

**Comment by stefanos82** [comment]
So `local a <const> = x` is not a `const` in C? :thinking:

**Comment by stefanos82** [comment]
lol forget what I wrote above; in my mind I saw them in reverse order :facepalm:

**Comment by edubart** [comment]
> So `local a <const> = x` is not a `const` in C? 

The `<const>` annotation is there to check at compile time for variable mutation (like in Lua), `<const>` in Nelua does not necessarily mean that the variable will be `const` in C. But some consts in Nelua depending on its semantics it will be `const` in C, note that this is usually not a problem because in C const does not impact performance, I've just added `const` in C code generator to suppress some warnings when dealing with const pointers, as side effect some integers are marked as const too and this is harmless, unless triggers a C compile error (this issue).

**Comment by stefanos82** [comment]
> But some consts in Nelua depending on its semantics it will be `const` in C, note that this is usually not a problem because in C const does not impact performance, I've just added `const` in C code generator to suppress some warnings when dealing with const pointers, as side effect some integers are marked as const too and this is harmless, unless triggers a C compile error (this issue).

Ah OK, I see.
