### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by 89z** [edubart/nelua-lang#96]
I think it would be helpful if you had compiled releases for the major platforms, something like this:

https://golang.org/dl

Doesnt need to be a build for every single commit, but even once a month would go a long way to onboarding people.

**Comment by codehz** [comment]
I created a windows binary release using github action and nightly.link https://nightly.link/codehz/nelua-lang/workflows/build/autobuild/windows.zip 
(modified the source to remove msys2/cygwin dependency, but you still need a gcc-compatiable compiler in path)

**Comment by 89z** [comment]
@codehz it works, you are cool!

**Comment by edubart** [comment]
> I created a windows binary release using github action and nightly.link https://nightly.link/codehz/nelua-lang/workflows/build/autobuild/windows.zip
> (modified the source to remove msys2/cygwin dependency, but you still need a gcc-compatiable compiler in path)

@codehz many thanks for taking some time to do that, I've added the `nelua.bat` script in the Nelua repository, also took the chance to improve support for Windows shells (Command Prompt/PowerShell). Users should now be able to compile and use Nelua in Visual Studio PowerShell with its Clang compiler, or use Nelua from Command Prompt using a GCC like compiler.

**Comment by edubart** [comment]
@codehz I've moved some files around in the repository, to make easy to compiler/install/package Nelua for Linux/Windows.

* `nelua` -> `lualib/nelua`
* `nelua.lua` -> `lualib/nelua.lua`
* `nelua.bat` is now available in the repository and was simplified and
* `src/nelua-lua.exe` -> `nelua-lua.exe`

So you may have to update the nightly script according the new changes

**Comment by codehz** [comment]
@edubart fixed

**Comment by edubart** [comment]
I've added in the repository a Github action to create binary package for Linux/Windows/MacOS at every commit, just go to https://github.com/edubart/nelua-lang/releases page and download once you want to update it. To use just extract and add the extracted folder to your system's `PATH`, also make sure you have a GCC or Clang compiler installed and also available in `PATH`.

Thanks @codehz for the initial Github action that motivated me doing that, and thanks @89z for the suggestion.
